ValueSet: ResultsLaboratoryObservation
Id: risultato-osservazione
Title: "Risultato Osservazione"
Description: "Valuset contente i codici che identificano il risultato dell'osservazione nel referto di laboratorio."
* ^status = #draft
* ^experimental = false
// * include codes from system $LOINC where STATUS = "ACTIVE" and CLASSTYPE = "1"
// * exclude codes from system $LOINC
//     where CLASS regex /CYTO|HL7\.CYTOGEN|HL7\.GENETICS|^PATH(\..*)?|^MOLPATH(\..*)?|NR STATS|H&P\.HX\.LAB|CHALSKIN|LABORDERS/

* $LOINC#1-8 "Acyclovir [Susceptibility]"
* $LOINC#10-9 "Amdinocillin [Susceptibility] by Serum bactericidal titer"
* $LOINC#100-8 "Cefoperazone [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#1000-9 "DBG Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#100041-3 "Aminoglycoside [Susceptibility]"
* $LOINC#100042-1 "Atovaquone [Susceptibility]"
* $LOINC#100043-9 "Azithromycin+Ethambutol [Susceptibility]"
* $LOINC#100044-7 "Cefcapene [Susceptibility]"
* $LOINC#100045-4 "Cefozopran [Susceptibility]"
* $LOINC#100046-2 "Cefquinome [Susceptibility]"
* $LOINC#100047-0 "Cefteram [Susceptibility]"
* $LOINC#100048-8 "Clarithromycin+Ethambutol [Susceptibility]"
* $LOINC#100049-6 "Eravacycline [Susceptibility]"
* $LOINC#100050-4 "Erythromycin+Ethambutol [Susceptibility]"
* $LOINC#100051-2 "Ethambutol+rifAMPin [Susceptibility]"
* $LOINC#100052-0 "Flomoxef [Susceptibility]"
* $LOINC#100053-8 "Fluoroquinolone [Susceptibility]"
* $LOINC#100054-6 "Gamithromycin [Susceptibility]"
* $LOINC#100055-3 "Optochin [Susceptibility]"
* $LOINC#100056-1 "Panipenem [Susceptibility]"
* $LOINC#100057-9 "Prothionamide [Susceptibility]"
* $LOINC#100058-7 "Prulifloxacin [Susceptibility]"
* $LOINC#100059-5 "Rifapentine [Susceptibility]"
* $LOINC#100060-3 "Tildipirosin [Susceptibility]"
* $LOINC#100061-1 "Tosufloxacin [Susceptibility]"
* $LOINC#100087-6 "Toxocara canis 24-35kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100088-4 "Taenia solium larva Ab bands panel - Serum by Immunoblot"
* $LOINC#100089-2 "Taenia solium larva 6-8kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100090-0 "Taenia solium larva 45kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100091-8 "Trypanosoma cruzi Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#100092-6 "Trypanosoma cruzi Ab bands panel - Serum by Immunoblot"
* $LOINC#100093-4 "Trypanosoma cruzi 15-16kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100094-2 "Trypanosoma cruzi 21-22kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100095-9 "Trypanosoma cruzi 27-28kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100096-7 "Trypanosoma cruzi 42kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100097-5 "Trypanosoma cruzi 45-47kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100098-3 "Trypanosoma cruzi 120-200kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100099-1 "Trypanosoma cruzi 160kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#1001-7 "DBG Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#100100-7 "Fasciola sp IgG Ab [Presence] in Serum by Immunoassay"
* $LOINC#100101-5 "Fasciola sp 8-9kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100102-3 "Fasciola sp 27-28kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100103-1 "Fasciola sp 60kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100104-9 "Fasciola sp 42kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100105-6 "Filaria IgG and IgM panel - Serum"
* $LOINC#100106-4 "Filaria IgG Ab [Presence] in Serum by Immunoassay"
* $LOINC#100107-2 "Leishmania sp IgG Ab [Presence] in Serum by Immunoassay"
* $LOINC#100108-0 "Leishmania sp IgG Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#100109-8 "Leishmania sp Ab bands panel - Serum by Immunoblot"
* $LOINC#100110-6 "Leishmania sp 14kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100111-4 "Leishmania sp 16kD IgG Ab [Presence] in Serum by Immunoblot"
* $LOINC#100112-2 "Fasciola sp Ab bands panel - Serum by Immunoblot"
* $LOINC#100113-0 "Helicobacter pylori Ab panel - Serum"
* $LOINC#100114-8 "Toxoplasma gondii 30kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100115-5 "Toxoplasma gondii 31kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100116-3 "Toxoplasma gondii 33kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100117-1 "Toxoplasma gondii 40kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100118-9 "Toxoplasma gondii 41kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100119-7 "Toxoplasma gondii 45kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100120-5 "Chlamydia trachomatis Ab panel - Serum"
* $LOINC#100121-3 "Chlamydia trachomatis IgA Ab [Presence] in Serum by Immunoassay"
* $LOINC#100122-1 "Chlamydophila pneumoniae Ab panel - Serum"
* $LOINC#100123-9 "Chlamydophila pneumoniae IgA Ab [Presence] in Serum by Immunoassay"
* $LOINC#100124-7 "Chlamydophila pneumoniae IgA Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#100125-4 "Chlamydophila psittaci Ab panel - Serum"
* $LOINC#100126-2 "Bordetella pertussis Ab.IgG panel - Serum"
* $LOINC#100127-0 "Campylobacter sp Ab panel - Serum"
* $LOINC#100128-8 "Cryptococcus sp Ag panel - Serum"
* $LOINC#100129-6 "Schistosoma sp Ab [Titer] in Serum by Hemagglutination"
* $LOINC#100130-4 "Schistosoma mansoni Ab [Presence] in Serum by Immunoblot"
* $LOINC#100131-2 "Schistosoma sp 8kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100132-0 "Schistosoma sp 9kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100133-8 "Schistosoma sp 10kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100134-6 "Schistosoma sp 11kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100135-3 "Schistosoma sp 12-13kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100136-1 "Schistosoma sp 14-15kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100137-9 "Schistosoma sp 15-16kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100138-7 "Schistosoma sp 18-19kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100139-5 "Schistosoma sp 22-24kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100140-3 "Schistosoma sp 30-34kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100141-1 "Schistosoma sp 65kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100142-9 "Schistosoma sp 70kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100143-7 "Schistosoma sp 80kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100144-5 "Schistosoma sp 95kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100145-2 "Schistosoma sp 110kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100146-0 "Schistosoma sp 120kD Ab [Presence] in Serum by Immunoblot"
* $LOINC#100147-8 "Toxoplasma gondii Ab bands panel - Serum by Immunoblot"
* $LOINC#100148-6 "Schistosoma sp Ab bands panel - Serum by Immunoblot"
* $LOINC#100149-4 "6-oxo-piperidine-2-carboxylate and 6(R+S)-oxo-propylpiperidine-2-carboxylate panel - Urine and Serum or Plasma"
* $LOINC#100150-2 "6(R+S)-oxo-propylpiperidine-2-carboxylate [Moles/volume] in Plasma"
* $LOINC#100151-0 "6-oxo-piperidine-2-carboxylate [Moles/volume] in Plasma"
* $LOINC#100152-8 "6-oxo-piperidine-2-carboxylate/Creatinine [Molar ratio] in Urine"
* $LOINC#100153-6 "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine [Molar ratio] in Urine"
* $LOINC#100154-4 "Specimen collection supervision level"
* $LOINC#100156-9 "SARS-CoV-2 (COVID-19) variant [Type] in Specimen by NAA with probe detection"
* $LOINC#100157-7 "SARS-CoV-2 (COVID-19) lineage [Type] in Specimen by Sequencing"
* $LOINC#100158-5 "Microalbumin [Mass/volume] in Urine collected for unspecified duration"
* $LOINC#1002-5 "DBG Ab [Presence] in Serum or Plasma"
* $LOINC#100281-5 "D Ab [Units/volume] in Serum or Plasma"
* $LOINC#1003-3 "Indirect antiglobulin test.complement specific reagent [Presence] in Serum or Plasma"
* $LOINC#100341-7 "Rubella virus IgG Ab index [Units/volume] in Serum and CSF"
* $LOINC#100342-5 "Volatile Organic Compounds associated with SARS-CoV-2 infection [Presence] in Exhaled gas by Gas chromatography-mass spectrometry"
* $LOINC#100343-3 "Influenza virus B RNA [Presence] in Saliva (oral fluid) by NAA with probe detection"
* $LOINC#100344-1 "Influenza virus A RNA [Presence] in Saliva (oral fluid) by NAA with probe detection"
* $LOINC#100345-8 "Influenza virus A and B and SARS-CoV-2 (COVID-19) RNA panel - Specimen by NAA with probe detection"
* $LOINC#100346-6 "Clotting time.extrinsic coagulation system activated.platelets inhibited of Blood by Rotational TEG"
* $LOINC#100347-4 "Clot formation.extrinsic coagulation system activated.platelets inhibited [Time] in Blood by Rotational TEG"
* $LOINC#100350-8 "Sesamum indicum 1 IgE Ab [Units/volume] in Serum"
* $LOINC#100351-6 "Pioglitazone [Presence] in Serum or Plasma"
* $LOINC#100352-4 "Rosiglitazone [Presence] in Serum or Plasma"
* $LOINC#100356-5 "Chlamydia trachomatis and Neisseria gonorrhoeae and Trichomonas vaginalis DNA [Identifier] in Specimen by NAA with probe detection"
* $LOINC#100357-3 "Naloxone [Presence] in Cord tissue by Screen method"
* $LOINC#100358-1 "Phentermine [Presence] in Cord tissue by Screen method"
* $LOINC#100359-9 "Gliadin 33 mer peptide [Mass/volume] in Stool by Immunoassay"
* $LOINC#100368-0 "Amino Acids Urea Cycle Panel - Serum or Plasma by LC/MS/MS"
* $LOINC#100370-6 "Orthopoxvirus DNA [Identifier] in Specimen by NAA with probe detection"
* $LOINC#100371-4 "Titin Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#100372-2 "Abiraterone [Mass/volume] in Serum or Plasma"
* $LOINC#100373-0 "Eucheuma IgG Ab [Units/volume] in Serum"
* $LOINC#100374-8 "Aloe vera IgG Ab [Units/volume] in Serum"
* $LOINC#100375-5 "Anise IgG Ab [Units/volume] in Serum"
* $LOINC#100376-3 "Bambusa vulgaris IgG Ab [Units/volume] in Serum"
* $LOINC#100377-1 "Goat cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100378-9 "Sheep cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100379-7 "Leeks IgG Ab [Units/volume] in Serum"
* $LOINC#100380-5 "Red cabbage IgG Ab [Units/volume] in Serum"
* $LOINC#100381-3 "Mentha balsamea Wild IgG Ab [Units/volume] in Serum"
* $LOINC#100383-9 "Monkeypox virus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100384-7 "Rapeseed IgG Ab [Units/volume] in Serum"
* $LOINC#100385-4 "Corn salad IgG Ab [Units/volume] in Serum"
* $LOINC#100386-2 "Rosemary IgG Ab [Units/volume] in Serum"
* $LOINC#100387-0 "Poppy Seed IgG Ab [Units/volume] in Serum"
* $LOINC#100388-8 "Cocoa IgG Ab [Units/volume] in Serum"
* $LOINC#100389-6 "Pistachio IgG Ab [Units/volume] in Serum"
* $LOINC#100390-4 "Sunflower Seed IgG Ab [Units/volume] in Serum"
* $LOINC#100391-2 "Dates IgG Ab [Units/volume] in Serum"
* $LOINC#100392-0 "Duck meat IgG Ab [Units/volume] in Serum"
* $LOINC#100393-8 "Allergen Mushroom mix 2 (Xerocomus, Boletus) IgG Ab [Units/volume] in Serum"
* $LOINC#100394-6 "Astacoidea IgG Ab [Units/volume] in Serum"
* $LOINC#100395-3 "Carob IgG Ab [Units/volume] in Serum"
* $LOINC#100396-1 "Brassica napus IgG Ab [Units/volume] in Serum"
* $LOINC#100397-9 "Goat Meat IgG Ab [Units/volume] in Serum"
* $LOINC#100398-7 "Goose meat IgG Ab [Units/volume] in Serum"
* $LOINC#100399-5 "Ostrich meat IgG Ab [Units/volume] in Serum"
* $LOINC#1004-1 "Direct antiglobulin test.complement specific reagent [Presence] on Red Blood Cells"
* $LOINC#100400-1 "Quail meat IgG Ab [Units/volume] in Serum"
* $LOINC#100401-9 "Rabbit meat IgG Ab [Units/volume] in Serum"
* $LOINC#100402-7 "Venison meat IgG Ab [Units/volume] in Serum"
* $LOINC#100403-5 "Guineafowl IgG Ab [Units/volume] in Serum"
* $LOINC#100404-3 "Horse meat IgG Ab [Units/volume] in Serum"
* $LOINC#100405-0 "Kefir IgG Ab [Units/volume] in Serum"
* $LOINC#100406-8 "Butter IgG Ab [Units/volume] in Serum"
* $LOINC#100407-6 "Camembert cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100408-4 "Emmental cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100409-2 "Processed cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100410-0 "Curd cheese IgG Ab [Units/volume] in Serum"
* $LOINC#100411-8 "Sugar Beet IgG Ab [Units/volume] in Serum"
* $LOINC#100412-6 "Chinese cabbage IgG Ab [Units/volume] in Serum"
* $LOINC#100413-4 "Fennel Fresh IgG Ab [Units/volume] in Serum"
* $LOINC#100414-2 "Gourd IgG Ab [Units/volume] in Serum"
* $LOINC#100415-9 "Kale IgG Ab [Units/volume] in Serum"
* $LOINC#100416-7 "Savoy cabbage IgG Ab [Units/volume] in Serum"
* $LOINC#100417-5 "Vitis sp leaf IgG Ab [Units/volume] in Serum"
* $LOINC#100418-3 "Liquorice IgG Ab [Units/volume] in Serum"
* $LOINC#100419-1 "Snow pea IgG Ab [Units/volume] in Serum"
* $LOINC#100420-9 "Fava bean IgG Ab [Units/volume] in Serum"
* $LOINC#100421-7 "Chick Pea IgG Ab [Units/volume] in Serum"
* $LOINC#100422-5 "Chicory IgG Ab [Units/volume] in Serum"
* $LOINC#100423-3 "Allergy Mushroom Mix 1 (Button + oyster + Shiitaki + chanterelle mushroom) IgG Ab [Units/volume] in Serum"
* $LOINC#100424-1 "8(9)-Cholestenol [Mass/volume] in Serum or Plasma"
* $LOINC#100425-8 "DiHydro T-Mas [Mass/volume] in Serum or Plasma"
* $LOINC#100426-6 "Squalene [Mass/volume] in Serum or Plasma"
* $LOINC#100427-4 "Stigmasterol [Mass/volume] in Serum or Plasma"
* $LOINC#100428-2 "Carnitine free and total and acylcarnitine panel - Urine"
* $LOINC#100429-0 "LRBA deficiency panel - Blood"
* $LOINC#100430-8 "Cells.LRBA+/100 Cells.CD3+CD14-CD45+ in Blood by Flow cytometry (FC)"
* $LOINC#100431-6 "Cells.CD3+CD14-CD45+.LRBA mean fluorescence intensity in Blood by Flow cytometry (FC)"
* $LOINC#100432-4 "Cells.LRBA+/100 Cells.CD3-CD14-CD19+CD45+ in Blood by Flow cytometry (FC)"
* $LOINC#100433-2 "Cells.CD3-CD14-CD19+CD45+.LRBA mean fluorescence intensity in Blood by Flow cytometry (FC)"
* $LOINC#100434-0 "Orthopoxvirus.non-variola DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100435-7 "Glial fibrillary acidic protein [Mass/volume] in Serum by Immunoassay"
* $LOINC#100436-5 "Ubiquitin carboxyl-terminal hydrolase-L1 [Mass/volume] in Serum by Immunoassay"
* $LOINC#100437-3 "Norsufentanil [Mass/volume] in Urine by Confirmatory method"
* $LOINC#1005-8 "Indirect antiglobulin test.IgG specific reagent [Presence] in Serum or Plasma"
* $LOINC#1006-6 "Direct antiglobulin test.IgG specific reagent [Interpretation] on Red Blood Cells"
* $LOINC#100654-3 "Pyruvate kinase M2 [Presence] in Stool"
* $LOINC#100662-6 "Cortisol free and total panel - Serum or Plasma"
* $LOINC#100671-7 "Aspergillus sp DNA [Presence] in Blood by NAA with probe detection"
* $LOINC#100672-5 "Aspergillus fumigatus DNA [Presence] in Blood by NAA with probe detection"
* $LOINC#100673-3 "Aspergillus terreus DNA [Presence] in Blood by NAA with probe detection"
* $LOINC#100674-1 "BK virus DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100675-8 "Cytomegalovirus DNA [Units/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100676-6 "Cytomegalovirus DNA [log units/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100677-4 "Epstein Barr virus DNA [Log #/volume] (viral load) in Serum or Plasma by NAA with probe detection"
* $LOINC#100678-2 "Epstein Barr virus DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100679-0 "Herpes virus 6 DNA [Log #/volume] (viral load) in Serum or Plasma by NAA with probe detection"
* $LOINC#100680-8 "Herpes virus 6 DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100681-6 "Herpes virus 7 DNA [Log #/volume] (viral load) in Serum or Plasma by NAA with probe detection"
* $LOINC#100682-4 "Herpes virus 7 DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100683-2 "Herpes virus 8 DNA [Log #/volume] (viral load) in Serum or Plasma by NAA with probe detection"
* $LOINC#100684-0 "Herpes virus 8 DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100685-7 "JC virus DNA [Log #/volume] (viral load) in Serum or Plasma by NAA with probe detection"
* $LOINC#100686-5 "JC virus DNA [Log #/volume] (viral load) in Cerebral spinal fluid by NAA with probe detection"
* $LOINC#100687-3 "JC virus DNA [Log #/volume] (viral load) in Urine by NAA with probe detection"
* $LOINC#100688-1 "Parvovirus B19 DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100689-9 "Toxoplasma gondii DNA [Log #/volume] in Serum or Plasma by NAA with probe detection"
* $LOINC#100690-7 "Toxoplasma gondii DNA [Log #/volume] in Cerebral spinal fluid by NAA with probe detection"
* $LOINC#100691-5 "Varicella zoster virus DNA [Log #/volume] (viral load) in Blood by NAA with probe detection"
* $LOINC#100692-3 "Varicella zoster virus DNA [Log #/volume] (viral load) in Cerebral spinal fluid by NAA with probe detection"
* $LOINC#100693-1 "Pneumocystis jiroveci DNA [Log #/volume] in Respiratory specimen by NAA with probe detection"
* $LOINC#100699-8 "Rifabutin+Ethambutol [Susceptibility]"
* $LOINC#1007-4 "Direct antiglobulin test.polyspecific reagent [Presence] on Red Blood Cells"
* $LOINC#100700-4 "Trichomonas vaginalis DNA [Presence] in Urethra by NAA with probe detection"
* $LOINC#100701-2 "Trichomonas vaginalis rRNA [Presence] in Urethra by NAA with probe detection"
* $LOINC#100702-0 "Mycoplasma genitalium rRNA [Presence] in Urethra by NAA with probe detection"
* $LOINC#100703-8 "Mycoplasma genitalium rRNA [Presence] in Urine by NAA with probe detection"
* $LOINC#100704-6 "Mycoplasma genitalium rRNA [Presence] in Cervix by NAA with probe detection"
* $LOINC#100705-3 "Mycoplasma genitalium rRNA [Presence] in Anorectal by NAA with probe detection"
* $LOINC#100706-1 "Mycoplasma genitalium rRNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100707-9 "Polymorphonuclear cells [#/volume] in Peritoneal dialysis fluid by Automated count"
* $LOINC#100708-7 "Plasma cells/100 leukocytes in Synovial fluid"
* $LOINC#100709-5 "Hepatocellular carcinoma risk [Score] by GAAD"
* $LOINC#100710-3 "Chlamydia trachomatis and Neisseria gonorrhoeae rRNA panel - Throat by NAA with probe detection"
* $LOINC#100711-1 "Borrelia burgdorferi.VlsE1+pepC10 Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#100712-9 "Brexpiprazole [Mass/volume] in Serum or Plasma"
* $LOINC#100713-7 "Cariprazine [Mass/volume] in Serum or Plasma"
* $LOINC#100714-5 "Guanfacine [Mass/volume] in Serum or Plasma"
* $LOINC#100715-2 "Prothipendyl [Mass/volume] in Serum or Plasma"
* $LOINC#100716-0 "Prostate specific Ag [Mass/volume] in DBS"
* $LOINC#100732-7 "Cholesterol.in lipoprotein (little a) and Cholesterol.in LDL panel - Serum"
* $LOINC#100733-5 "Cholesterol in LDL [Mass/volume] in Serum by calculation --corrected for Cholesterol.in lipoprotein (little a)"
* $LOINC#100734-3 "traMADol and Metabolites Panel - Urine by Confirmatory method"
* $LOINC#100735-0 "Mannose-6-phosphate isomerase and phosphomannomutase 1 panel - Leukocytes"
* $LOINC#100736-8 "Acylcarnitine Analysis Post Mortem in Specimen Document"
* $LOINC#100737-6 "Alkaline phosphatase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100738-4 "Alanine aminotransferase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100739-2 "Aspartate aminotransferase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100740-0 "Amylase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100741-8 "Gamma glutamyl transferase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100742-6 "Lactate dehydrogenase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100743-4 "Lipase.macromolecular [Presence] in Serum or Plasma"
* $LOINC#100744-2 "Alpha-1-acid glycoprotein [Mass/volume] in Serum or Plasma by Electrophoresis"
* $LOINC#100745-9 "Chloride [Moles/volume] in Mixed venous blood"
* $LOINC#100746-7 "Glucose [Moles/volume] in Mixed venous blood"
* $LOINC#100747-5 "Legionella serogroup panel - Specimen"
* $LOINC#100748-3 "Legionella spp [Presence] in Specimen by NAA with probe detection"
* $LOINC#100749-1 "Legionella pneumophila serogroup 1 [Presence] in Specimen by NAA with probe detection"
* $LOINC#100750-9 "Legionella pneumophila non-serogroup 1 [Presence] in Specimen by NAA with probe detection"
* $LOINC#100751-7 "Galactose-alpha-1,3-galactose (Alpha-Gal) panel - Serum or Plasma"
* $LOINC#100755-8 "Oligoclonal bands [#] in Serum or Plasma by Isoelectric focusing"
* $LOINC#100756-6 "Oligoclonal bands [Interpretation] in Cerebral spinal fluid by Isoelectric focusing"
* $LOINC#100757-4 "Protein fractions.oligoclonal bands panel - Serum and CSF by Isoelectric focusing"
* $LOINC#100765-7 "Homocysteine and methylmalonate and methylcitrate panel - DBS"
* $LOINC#100788-9 "Stemphylium botryosum IgG4 Ab [Mass/volume] in Serum"
* $LOINC#100789-7 "Rhizopus nigricans IgG4 Ab [Mass/volume] in Serum"
* $LOINC#100790-5 "Lepidoglyphus destructor IgG Ab [Mass/volume] in Serum"
* $LOINC#100791-3 "Hamster epithelium IgG Ab [Mass/volume] in Serum"
* $LOINC#100792-1 "Forsythia IgE Ab [Units/volume] in Serum"
* $LOINC#100793-9 "Testosterone [Mass/volume] in Body fluid"
* $LOINC#100794-7 "Follitropin [Units/volume] in Body fluid"
* $LOINC#100795-4 "S100 calcium binding protein B [Mass/volume] in Body fluid"
* $LOINC#100796-2 "Thyroglobulin [Mass/volume] in Body fluid"
* $LOINC#100797-0 "Testosterone Free [Mass/volume] in Serum --1st specimen post XXX challenge"
* $LOINC#100798-8 "Testosterone Free [Mass/volume] in Serum --2nd specimen post XXX challenge"
* $LOINC#100799-6 "21-Deoxycortisol [Mass/volume] in Serum --1st specimen post XXX challenge"
* $LOINC#1008-2 "Indirect antiglobulin test.polyspecific reagent [Presence] in Serum or Plasma"
* $LOINC#100800-2 "21-Deoxycortisol [Mass/volume] in Serum --2nd specimen post XXX challenge"
* $LOINC#100801-0 "21-Deoxycortisol [Mass/volume] in Serum --3rd specimen post XXX challenge"
* $LOINC#100802-8 "21-Deoxycortisol [Mass/volume] in Serum --4th specimen post XXX challenge"
* $LOINC#100803-6 "21-Deoxycortisol [Mass/volume] in Serum --5th specimen post XXX challenge"
* $LOINC#100804-4 "Vasopressin [Moles/volume] in Plasma --1st specimen post XXX challenge"
* $LOINC#100805-1 "Vasopressin [Moles/volume] in Plasma --2nd specimen post XXX challenge"
* $LOINC#100806-9 "Vasopressin [Moles/volume] in Plasma --3rd specimen post XXX challenge"
* $LOINC#100807-7 "Vasopressin [Moles/volume] in Plasma --4th specimen post XXX challenge"
* $LOINC#100808-5 "Vasopressin [Moles/volume] in Plasma --5th specimen post XXX challenge"
* $LOINC#100809-3 "Vasopressin [Moles/volume] in Plasma --6th specimen post XXX challenge"
* $LOINC#100810-1 "Vasopressin [Moles/volume] in Plasma --7th specimen post XXX challenge"
* $LOINC#100811-9 "Vasopressin [Moles/volume] in Plasma --8th specimen post XXX challenge"
* $LOINC#100812-7 "Vasopressin [Moles/volume] in Plasma --9th specimen post XXX challenge"
* $LOINC#100813-5 "Vasopressin [Moles/volume] in Plasma --10th specimen post XXX challenge"
* $LOINC#100814-3 "Vasopressin [Moles/volume] in Plasma --11th specimen post XXX challenge"
* $LOINC#100815-0 "Vasopressin [Moles/volume] in Plasma --12th specimen post XXX challenge"
* $LOINC#100816-8 "Glucagon [Mass/volume] in Serum or Plasma --6th specimen post XXX challenge"
* $LOINC#100817-6 "Glucagon [Mass/volume] in Serum or Plasma --7th specimen post XXX challenge"
* $LOINC#100818-4 "Renin [Mass/volume] in Plasma --1st specimen post XXX challenge"
* $LOINC#100819-2 "Renin [Mass/volume] in Plasma --2nd specimen post XXX challenge"
* $LOINC#100820-0 "Renin [Mass/volume] in Plasma --3rd specimen post XXX challenge"
* $LOINC#100829-1 "Renin [Mass/volume] in Plasma --4th specimen post XXX challenge"
* $LOINC#100830-9 "Alpha subunit free [Units/volume] in Serum or Plasma --1st specimen post XXX challenge"
* $LOINC#100831-7 "Alpha subunit free [Units/volume] in Serum or Plasma --2nd specimen post XXX challenge"
* $LOINC#100832-5 "Alpha subunit free [Units/volume] in Serum or Plasma --3rd specimen post XXX challenge"
* $LOINC#100833-3 "Alpha subunit free [Units/volume] in Serum or Plasma --4th specimen post XXX challenge"
* $LOINC#100834-1 "Alpha subunit free [Units/volume] in Serum or Plasma --5th specimen post XXX challenge"
* $LOINC#100835-8 "Alpha subunit free [Units/volume] in Serum or Plasma --6th specimen post XXX challenge"
* $LOINC#100836-6 "Alpha subunit free [Units/volume] in Serum or Plasma --7th specimen post XXX challenge"
* $LOINC#100837-4 "Insulin-like growth factor-I [Mass/volume] in Serum or Plasma --9th specimen post XXX challenge"
* $LOINC#100838-2 "Testosterone [Mass/volume] in Serum or Plasma --9th specimen post XXX challenge"
* $LOINC#100839-0 "Vitamin A/Retinol binding protein [Ratio] in Serum or Plasma"
* $LOINC#100840-8 "IgE [Units/volume] in Body fluid"
* $LOINC#100841-6 "Zinc finger protein of the cerebellum 4 Ab [Presence] in Cerebral spinal fluid by Line blot"
* $LOINC#100842-4 "Nonalcoholic steatohepatitis score in Serum or Plasma Calculated by FAST"
* $LOINC#100843-2 "Liver fibrosis score in Serum or Plasma by Calculated.Agile3+"
* $LOINC#100844-0 "Liver fibrosis score in Serum or Plasma by Calculated.Agile4"
* $LOINC#100845-7 "Neurofascin155 IgG4 Ab [Presence] in Serum by Flow cytometry (FC)"
* $LOINC#100846-5 "Dengue virus 1+2+3+4 nsP1 IgG Ab [Presence] in Serum or Plasma by Immunoassay"
* $LOINC#100847-3 "Gas and ammonia panel - Arterial blood"
* $LOINC#100848-1 "Cell count and Differential panel - Amniotic fluid by Manual count"
* $LOINC#100849-9 "Leukocytes [#/volume] in Amniotic fluid by Manual count"
* $LOINC#100850-7 "Neutrophils [#/volume] in Amniotic fluid by Manual count"
* $LOINC#100851-5 "Other cells [#/volume] in Amniotic fluid by Manual count"
* $LOINC#100854-9 "Lymphocytes/100 cells in Blood mononuclear cells by Immunoassay"
* $LOINC#100855-6 "CD3 cells/100 cells in Blood mononuclear cells"
* $LOINC#100856-4 "CD3+CD4+ (T4 helper) cells/100 cells in Blood mononuclear cells"
* $LOINC#100857-2 "CD3+CD8+ (T8 suppressor) cells/100 cells in Blood mononuclear cells"
* $LOINC#100858-0 "Cells.CD4+CD154+/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* $LOINC#100859-8 "Cells.CD4.Interferon gamma-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* $LOINC#100860-6 "Cells.CD4.Tumor necrosis factor alfa-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* $LOINC#100861-4 "Cells.CD4+CD154+/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* $LOINC#100862-2 "Cells.CD4.Interferon gamma-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* $LOINC#100863-0 "Cells.CD4.Tumor necrosis factor alfa-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* $LOINC#100864-8 "Giardia lamblia bg gene [Genotype] in Specimen by Molecular genetics method"
* $LOINC#100865-5 "Avian schistosomes DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100866-3 "Febrile antibody profile in Serum"
* $LOINC#100867-1 "Campylobacter jejuni+coli+lari+upsaliensis Ag [Presence] in Stool by Rapid immunoassay"
* $LOINC#100868-9 "Cryptosporidium sp 18S-LC2 rRNA [Genotype] in Specimen by Molecular genetics method"
* $LOINC#100869-7 "Cryptosporidium gp60 gene [Type] in Specimen by Molecular genetics method"
* $LOINC#100870-5 "Cryptosporidium 18S rRNA [Genotype] in Specimen by Molecular genetics method"
* $LOINC#100871-3 "Giardia lamblia gdh gene [Genotype] in Specimen by Molecular genetics method"
* $LOINC#100872-1 "Bacteria producing polysaccharide from sucrose [Presence] in Isolate"
* $LOINC#100873-9 "Giardia lamblia tpi gene [Genotype] in Specimen by Molecular genetics method"
* $LOINC#100874-7 "Basidiobolus sp [Presence] in Specimen"
* $LOINC#100885-3 "Parapoxvirus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100886-1 "Orf virus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100887-9 "Pseudocowpox virus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100888-7 "West African monkeypox virus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100889-5 "Congo Basin monkeypox virus DNA [Presence] in Specimen by NAA with probe detection"
* $LOINC#100890-3 "Poxvirus DNA panel"
* $LOINC#100891-1 "Orthopoxvirus IgG Ab [Presence] in Serum or Plasma by Immunoassay"
* $LOINC#100892-9 "Orthopoxvirus IgM Ab [Presence] in Serum or Plasma by Immunoassay"
* $LOINC#100893-7 "Orthopoxvirus IgG and IgM Ab panel - Serum or Plasma"
* $LOINC#100895-2 "Rickettsia conorii IgG and IgM [Interpretation] in Serum"
* $LOINC#100896-0 "Vasopressin [Moles/volume] in Plasma --13th specimen post XXX challenge"
* $LOINC#100897-8 "Staphylococcus aureus [Presence] in Specimen by Organism specific culture"
* $LOINC#100898-6 "Lipid panel - Serum or Plasma"
* $LOINC#100899-4 "Enterobacteriaceae.extended spectrum beta lactamase resistance phenotype [Identifier] in Specimen by Organism specific culture"
* $LOINC#1009-0 "Deprecated Direct antiglobulin test.poly specific reagent [Presence] on Red Blood Cells"
* $LOINC#100900-0 "Enterobacteriaceae.carbapenem resistance panel - Anal by Organism specific culture"
* $LOINC#100901-8 "Enterobacteriaceae.carbapenemase resistance phenotype [Identifier] in Anal by Organism specific culture"
* $LOINC#100902-6 "Enterobacteriaceae.carbapenemase resistance phenotype.OXA-48 [Identifier] in Anal by Organism specific culture"
* $LOINC#100903-4 "Yeast and Candida sp identification panel - Specimen by Organism specific culture"
* $LOINC#100904-2 "Urinary tract pathogens panel - Urine by Culture"
* $LOINC#100905-9 "Gram positive bacteria identified in Isolate by Organism specific culture"
* $LOINC#100906-7 "Bacteria [#/volume] in Urine by Culture"
* $LOINC#100907-5 "Vancomycin resistant enterococcus [Identifier] in Specimen by Organism specific culture"
* $LOINC#100908-3 "Pseudomonas aeruginosa [Presence] in Lower respiratory specimen by Organism specific culture"
* $LOINC#100909-1 "Cronobacter sakazakii [Presence] by Organism specific culture"
* $LOINC#100910-9 "Gram negative bacteria.colistin resistant identified in Stool by Organism specific culture"
* $LOINC#100911-7 "Campylobacter sp [Presence] in Stool by Organism specific culture"
* $LOINC#100912-5 "Enterobacteriaceae.extended spectrum beta lactamase resistance phenotype and Enterococcus species.vancomycin resistant panel"
* $LOINC#100913-3 "Staph aureus and MRSA screening panel - Specimen by Organism specific culture"
* $LOINC#100914-1 "Protein.abnormal band [Mass/volume] in Serum or Plasma by Electrophoresis"
* $LOINC#100915-8 "Burr cells [Presence] in Body fluid by Light microscopy"
* $LOINC#100962-0 "Dengue virus Ab.IgG Panel - Serum, Plasma or Blood"
* $LOINC#100963-8 "Dengue virus 1+2+3+4 nsP1 IgG Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $LOINC#100964-6 "Dengue virus IgG Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* $LOINC#100965-3 "Dengue virus IgG Ab [Interpretation] in Serum, Plasma or Blood"
* $LOINC#100968-7 "Bovine tuberculosis comparative cervical test panel - Skin"
* $LOINC#101-6 "Cefoperazone [Susceptibility] by Disk diffusion (KB)"
* $LOINC#1010-8 "E sup(w) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#1011-6 "E sup(w) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#1012-4 "E sup(w) Ab [Presence] in Serum or Plasma"
* $LOINC#1013-2 "E sup(w) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#1014-0 "E sup(w) Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#1015-7 "E sup(w) Ag [Presence] on Red Blood Cells"
* $LOINC#1016-5 "E Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#1017-3 "E Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#1018-1 "E Ab [Presence] in Serum or Plasma"
* $LOINC#1019-9 "E Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#102-4 "Cefoperazone [Susceptibility] by Serum bactericidal titer"
* $LOINC#1020-7 "E Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#1021-5 "E Ag [Presence] on Red Blood Cells"
* $LOINC#1022-3 "Fy sup(a) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10226-9 "Oxygen content in Intravascular space"
* $LOINC#1023-1 "Fy sup(a) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10232-7 "Oxygen content in Aorta root"
* $LOINC#10233-5 "Oxygen content in Left atrium"
* $LOINC#10234-3 "Oxygen content in Right atrium"
* $LOINC#10235-0 "Oxygen content in High right atrium"
* $LOINC#10236-8 "Oxygen content in Low right atrium"
* $LOINC#10237-6 "Oxygen content in Mid right atrium"
* $LOINC#10238-4 "Oxygen content in Left ventricle"
* $LOINC#10239-2 "Oxygen content in Right ventricular outflow tract"
* $LOINC#1024-9 "Fy sup(a) Ab [Presence] in Serum or Plasma"
* $LOINC#10240-0 "Oxygen content in Right ventricle"
* $LOINC#10241-8 "Oxygen content in Coronary sinus"
* $LOINC#10242-6 "Oxygen content in Ductus arteriosus"
* $LOINC#10243-4 "Oxygen content in Inferior vena cava"
* $LOINC#10244-2 "Oxygen content in Left pulmonary artery"
* $LOINC#10245-9 "Oxygen content in Main pulmonary artery"
* $LOINC#10246-7 "Oxygen content in Right pulmonary artery"
* $LOINC#10247-5 "Oxygen content in Pulmonary wedge"
* $LOINC#10248-3 "Oxygen content in Superior vena cava"
* $LOINC#1025-6 "Fy sup(a) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#1026-4 "Fy sup(a) Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#1027-2 "Fy sup(a) Ag [Presence] on Red Blood Cells"
* $LOINC#1028-0 "Fy sup(b) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#1029-8 "Fy sup(b) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#103-2 "Ceforanide [Susceptibility] by Minimum lethal concentration (MLC)"
* $LOINC#1030-6 "Fy sup(b) Ab [Presence] in Serum or Plasma"
* $LOINC#1031-4 "Fy sup(b) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#1032-2 "Fy sup(b) Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10327-5 "Eosinophils/100 leukocytes in Sputum by Manual count"
* $LOINC#10328-3 "Lymphocytes/100 leukocytes in Cerebral spinal fluid by Manual count"
* $LOINC#10329-1 "Monocytes/100 leukocytes in Cerebral spinal fluid by Manual count"
* $LOINC#1033-0 "Fy sup(b) Ag [Presence] on Red Blood Cells"
* $LOINC#10330-9 "Monocytes/100 leukocytes in Body fluid by Manual count"
* $LOINC#10331-7 "Rh [Type] in Blood"
* $LOINC#10332-5 "Cortisol [Mass/volume] in Serum or Plasma --pre 250 ug corticotropin IM"
* $LOINC#10333-3 "Appearance of Cerebral spinal fluid"
* $LOINC#10334-1 "Cancer Ag 125 [Units/volume] in Serum or Plasma"
* $LOINC#10335-8 "Color of Cerebral spinal fluid"
* $LOINC#10336-6 "Gonadotropin peptide [Mass/volume] in Urine"
* $LOINC#10337-4 "Procollagen type I [Mass/volume] in Serum"
* $LOINC#10338-2 "Barbiturates [Mass/volume] in Serum or Plasma"
* $LOINC#10339-0 "FLUoxetine+Norfluoxetine [Mass/volume] in Serum or Plasma"
* $LOINC#1034-8 "Fetal cell screen [Interpretation] in Blood"
* $LOINC#10340-8 "Molindone [Mass/volume] in Serum or Plasma"
* $LOINC#10341-6 "Norpropoxyphene [Mass/volume] in Serum or Plasma"
* $LOINC#10342-4 "Sulfamethoxazole [Mass/volume] in Serum or Plasma"
* $LOINC#10343-2 "Temazepam [Mass/volume] in Serum or Plasma"
* $LOINC#10344-0 "Tranylcypromine [Mass/volume] in Serum or Plasma"
* $LOINC#10345-7 "Trihexyphenidyl [Mass/volume] in Urine"
* $LOINC#10346-5 "Hemoglobin A [Units/volume] in Blood by Electrophoresis"
* $LOINC#10347-3 "Babesia microti identified in Blood by Light microscopy"
* $LOINC#10348-1 "Bordetella parapertussis Ab [Presence] in Serum"
* $LOINC#10349-9 "Brucella sp Ab [Units/volume] in Serum"
* $LOINC#1035-5 "Fresh frozen plasma given [Volume]"
* $LOINC#10350-7 "Herpes simplex virus IgM Ab [Titer] in Serum by Immunoassay"
* $LOINC#10351-5 "HIV 1 RNA [Units/volume] (viral load) in Serum or Plasma by Probe with amplification"
* $LOINC#10352-3 "Bacteria identified in Genital specimen by Aerobe culture"
* $LOINC#10353-1 "Bacteria identified in Nose by Aerobe culture"
* $LOINC#10354-9 "Bacteria identified in Urethra by Culture"
* $LOINC#10355-6 "Microscopic observation [Identifier] in Bone marrow by Wright Giemsa stain"
* $LOINC#10356-4 "Deprecated Microscopic observation [Identifier] in Stool by Trichrome stain"
* $LOINC#10357-2 "Microscopic observation [Identifier] in Wound by Gram stain"
* $LOINC#10358-0 "Teichoate Ab [Titer] in Serum by Immune diffusion (ID)"
* $LOINC#10359-8 "Asialoganglioside GM1 IgM Ab [Titer] in Serum"
* $LOINC#1036-3 "G Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10360-6 "DNA single strand IgG Ab [Units/volume] in Serum"
* $LOINC#10361-4 "DNA single strand IgM Ab [Units/volume] in Serum"
* $LOINC#10362-2 "Endomysium IgA Ab [Presence] in Serum"
* $LOINC#10363-0 "Barbiturates [Presence] in Specimen"
* $LOINC#10364-8 "Cotinine [Mass/mass] in Hair"
* $LOINC#10365-5 "Cotinine [Mass/volume] in Serum or Plasma"
* $LOINC#10366-3 "Cotinine [Mass/volume] in Urine"
* $LOINC#10367-1 "Ethanol [Mass/volume] in Gastric fluid"
* $LOINC#10368-9 "Lead [Mass/volume] in Capillary blood"
* $LOINC#10369-7 "Opiates [Mass/mass] in Hair"
* $LOINC#1037-1 "G Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10370-5 "Phencyclidine [Mass/mass] in Hair"
* $LOINC#10371-3 "Bite cells [Presence] in Blood by Light microscopy"
* $LOINC#10372-1 "Blister cells [Presence] in Blood by Light microscopy"
* $LOINC#10373-9 "Fragments [Presence] in Blood by Light microscopy"
* $LOINC#10374-7 "Helmet cells [Presence] in Blood by Light microscopy"
* $LOINC#10375-4 "Irregularly contracted cells [Presence] in Blood by Light microscopy"
* $LOINC#10376-2 "Oval macrocytes [Presence] in Blood by Light microscopy"
* $LOINC#10377-0 "Pencil cells [Presence] in Blood by Light microscopy"
* $LOINC#10378-8 "Polychromasia [Presence] in Blood by Light microscopy"
* $LOINC#10379-6 "Erythrocytes.dual population [Presence] in Blood by Light microscopy"
* $LOINC#1038-9 "G Ab [Presence] in Serum or Plasma"
* $LOINC#10380-4 "Stomatocytes [Presence] in Blood by Light microscopy"
* $LOINC#10381-2 "Target cells [Presence] in Blood by Light microscopy"
* $LOINC#10382-0 "Deprecated A,B variant NOS Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10383-8 "Deprecated A,B variant NOS Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10384-6 "Deprecated A,B variant NOS Ag [Presence] on Red Blood Cells"
* $LOINC#10385-3 "Albumin concentration given"
* $LOINC#10386-1 "Albumin given [Volume]"
* $LOINC#10387-9 "Autologous erythrocytes given [Volume]"
* $LOINC#10388-7 "Autologous whole blood given [Volume]"
* $LOINC#10389-5 "Blood product.other [Type]"
* $LOINC#1039-7 "G Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10390-3 "Blood product special preparation [Type]"
* $LOINC#10391-1 "Cytomegalovirus immune globulin given [Volume]"
* $LOINC#10392-9 "Cryoprecipitate given [Volume]"
* $LOINC#10393-7 "Factor IX given [Type]"
* $LOINC#10394-5 "Factor IX given [Volume]"
* $LOINC#10395-2 "Factor VIII given [Type]"
* $LOINC#10396-0 "Factor VIII given [Volume]"
* $LOINC#10397-8 "Hepatitis B immune globulin given [Volume]"
* $LOINC#10398-6 "I Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10399-4 "I Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#104-0 "Ceforanide [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#1040-5 "G Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10400-0 "I Ag [Presence] on Red Blood Cells"
* $LOINC#10401-8 "Immune serum globulin given [Type]"
* $LOINC#10402-6 "Immune serum globulin given [Volume]"
* $LOINC#10403-4 "Inject immune serum globulin [Volume]"
* $LOINC#10404-2 "Inject Rh immune globulin [Volume]"
* $LOINC#10405-9 "Inject varicella zoster virus immune globulin [Volume]"
* $LOINC#10406-7 "little i Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10407-5 "little i Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10408-3 "little i Ag [Presence] on Red Blood Cells"
* $LOINC#10409-1 "Pentaspan given [Volume]"
* $LOINC#1041-3 "G Ag [Presence] on Red Blood Cells"
* $LOINC#10410-9 "Plasma given [Type]"
* $LOINC#10411-7 "Plasma given [Volume]"
* $LOINC#10412-5 "Platelets given [Type]"
* $LOINC#10413-3 "Rh immune globulin given [Volume]"
* $LOINC#10414-1 "Transfuse albumin [Volume]"
* $LOINC#10415-8 "Transfuse blood exchange transfusion [Volume]"
* $LOINC#10416-6 "Transfuse blood product other [Volume]"
* $LOINC#10417-4 "Transfuse cryoprecipitate [Volume]"
* $LOINC#10418-2 "Transfuse factor IX [Volume]"
* $LOINC#10419-0 "Transfuse factor VIII [Volume]"
* $LOINC#1042-1 "H Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10420-8 "Transfuse immune serum globulin [Volume]"
* $LOINC#10421-6 "Transfuse Pentaspan [Volume]"
* $LOINC#10422-4 "Transfuse plasma [Volume]"
* $LOINC#10423-2 "Transfuse platelets [Volume]"
* $LOINC#10424-0 "Transfuse erythrocytes [Volume]"
* $LOINC#10425-7 "Transfuse Rh immune globulin [Volume]"
* $LOINC#10426-5 "Transfuse whole blood [Volume]"
* $LOINC#10427-3 "Transfuse whole blood autologous [Volume]"
* $LOINC#10428-1 "Varicella zoster virus immune globulin given [Volume]"
* $LOINC#10429-9 "AE 1 Ag [Presence] in Tissue by Immune stain"
* $LOINC#1043-9 "H Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10430-7 "AE 3 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10431-5 "B-cell Ag [Presence] in Tissue by Immune stain"
* $LOINC#10432-3 "CD30 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10433-1 "BR-2 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10434-9 "Complement C3 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10435-6 "C5B-9 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10436-4 "CD15 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10437-2 "CD16 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10438-0 "CD20 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10439-8 "CD3 Ag [Presence] in Tissue by Immune stain"
* $LOINC#1044-7 "H Ab [Presence] in Serum"
* $LOINC#10440-6 "Deprecated CD30 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10441-4 "CD34 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10442-2 "CD56 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10443-0 "CD43 T-cell monocyte+myeloid cell Ag [Presence] in Tissue by Immune stain"
* $LOINC#10444-8 "CD57 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10445-5 "CD11c Ag [Presence] in Tissue by Immune stain"
* $LOINC#10446-3 "Leukocyte common Ag [Presence] in Tissue by Immune stain"
* $LOINC#10447-1 "M-5 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10448-9 "T-cell Ag [Presence] in Tissue by Immune stain"
* $LOINC#10449-7 "Glucose [Mass/volume] in Serum or Plasma --1 hour post meal"
* $LOINC#1045-4 "Deprecated H NOS Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10450-5 "Glucose [Mass/volume] in Serum or Plasma --10 hours fasting"
* $LOINC#10451-3 "Proinsulin [Moles/volume] in Serum or Plasma --12 hours fasting"
* $LOINC#10452-1 "Xylose [Mass/volume] in Serum or Plasma --1 hour post 25 g xylose PO"
* $LOINC#10453-9 "Xylose [Mass/volume] in Serum or Plasma --1 hour post dose xylose PO"
* $LOINC#10454-7 "Xylose [Mass/volume] in Serum or Plasma --2 hours post 25 g xylose PO"
* $LOINC#10455-4 "Xylose [Mass/volume] in Serum or Plasma --30 minutes post 25 g xylose PO"
* $LOINC#10456-2 "Xylose [Mass/volume] in Serum or Plasma --6 hours fasting"
* $LOINC#1046-2 "Deprecated H NOS Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10466-1 "Anion gap 3 in Serum or Plasma"
* $LOINC#1047-0 "Deprecated H NOS Ab [Presence] in Serum or Plasma"
* $LOINC#10479-4 "CD227 Ag [Presence] in Tissue by Immune stain"
* $LOINC#1048-8 "Deprecated H NOS Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#1049-6 "Deprecated H NOS Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#105-7 "Ceforanide [Susceptibility] by Disk diffusion (KB)"
* $LOINC#1050-4 "Deprecated H NOS Ag [Presence] on Red Blood Cells"
* $LOINC#10501-5 "Lutropin [Units/volume] in Serum or Plasma"
* $LOINC#1051-2 "Hemolytic disease of newborn screen [Interpretation] in Blood"
* $LOINC#1052-0 "Deprecated I (intermediate) subtype [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10520-5 "Coagulation factor VI Ag [Presence] in Tissue by Immune stain"
* $LOINC#10521-3 "Coagulation factor VIII Ag [Presence] in Tissue by Immune stain"
* $LOINC#10522-1 "Coagulation factor XIII Ag [Presence] in Tissue by Immune stain"
* $LOINC#10523-9 "Fibrinogen Ag [Presence] in Tissue by Immune stain"
* $LOINC#10528-8 "Acetophenazine [Mass/volume] in Serum or Plasma"
* $LOINC#10529-6 "Amoxapine metabolite [Mass/volume] in Serum or Plasma"
* $LOINC#1053-8 "Deprecated I (intermediate) subtype [Presence] in serum or plasma from donor"
* $LOINC#10530-4 "Aprobarbital [Mass/volume] in Serum or Plasma"
* $LOINC#10531-2 "Bretylium [Mass/volume] in Serum or Plasma"
* $LOINC#10532-0 "Deprecated Desethylamiodarone [Mass/volume] in Serum or Plasma"
* $LOINC#10533-8 "Propoxyphene+Acetaminophen [Mass/volume] in Serum or Plasma"
* $LOINC#10534-6 "Diazoxide [Mass/volume] in Serum or Plasma"
* $LOINC#10535-3 "Digoxin [Mass/volume] in Serum or Plasma"
* $LOINC#10536-1 "Dipyridamole [Mass/volume] in Serum or Plasma"
* $LOINC#10537-9 "Deprecated Doxepin+Nordoxepin [Mass/volume] in Serum or Plasma"
* $LOINC#10538-7 "Deprecated Fluoxetine+Norfluoxetine [Mass/volume] in Serum or Plasma"
* $LOINC#10539-5 "glipiZIDE [Mass/volume] in Serum or Plasma"
* $LOINC#1054-6 "Deprecated I (intermediate) subtype [Presence] in srum"
* $LOINC#10540-3 "glyBURIDE [Mass/volume] in Serum or Plasma"
* $LOINC#10541-1 "Mepivacaine [Mass/volume] in Serum or Plasma"
* $LOINC#10542-9 "Metharbital [Mass/volume] in Serum or Plasma"
* $LOINC#10543-7 "Methsuximide+Normethsuximide [Mass/volume] in Serum or Plasma"
* $LOINC#10544-5 "Normeperidine [Presence] in Serum or Plasma"
* $LOINC#10545-2 "Normephenytoin [Mass/volume] in Serum or Plasma"
* $LOINC#10546-0 "Normethsuximide [Mass/volume] in Serum or Plasma"
* $LOINC#10547-8 "Primidone+PHENobarbital [Mass/volume] in Serum or Plasma"
* $LOINC#10548-6 "Phenytoin Free/Phenytoin.total in Serum or Plasma"
* $LOINC#10549-4 "Pirmenol [Mass/volume] in Serum or Plasma"
* $LOINC#1055-3 "Deprecated I (intermediate) subtype [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10550-2 "Deprecated Temazepam [Mass/volume] in Serum or Plasma"
* $LOINC#10551-0 "Triamterene [Mass/volume] in Serum or Plasma"
* $LOINC#10552-8 "Tricyclic antidepressants [Mass/volume] in Serum or Plasma"
* $LOINC#10553-6 "Prostatic acid phosphatase [Enzymatic activity/volume] in Genital fluid"
* $LOINC#10554-4 "Deprecated Prostatic acid phosphatase [Enzymatic activity/volume] in Seminal plasma"
* $LOINC#10555-1 "Acrosin [Entitic Catalytic Activity] in Spermatozoa"
* $LOINC#10556-9 "Deprecated Adenosine triphosphatase [Enzymatic activity/volume] in Seminal plasma"
* $LOINC#10557-7 "Adenosine triphosphate [Moles/volume] in Semen"
* $LOINC#10558-5 "Albumin [Moles/volume] in Semen"
* $LOINC#10559-3 "Deprecated Calcium [Molecules/volume] in Semen"
* $LOINC#1056-1 "Deprecated I (intermediate) subtype [Presence] on Red Blood Cells from donor"
* $LOINC#10560-1 "Carcinoembryonic Ag [Units/volume] in Semen"
* $LOINC#10561-9 "Carnitine [Moles/volume] in Semen"
* $LOINC#10562-7 "Cells [#/volume] in Cervical mucus"
* $LOINC#10563-5 "Cells other than spermatozoa [#/volume] in Semen"
* $LOINC#10564-3 "Cervical mucus [Volume]"
* $LOINC#10565-0 "Choriogonadotropin [Units/volume] in Semen"
* $LOINC#10566-8 "Deprecated Choriogonadotropin [Molecules/volume] in Semen"
* $LOINC#10567-6 "Citrate [Moles/volume] in Semen"
* $LOINC#10568-4 "Clarity of Semen"
* $LOINC#10569-2 "Color of Semen"
* $LOINC#1057-9 "Deprecated I (intermediate) subtype [Presence] on Red Blood Cells"
* $LOINC#10570-0 "Consistency of Cervical mucus"
* $LOINC#10571-8 "Deprecated Consistency of Semen"
* $LOINC#10572-6 "Deprecated Duration^post ejaculation"
* $LOINC#10573-4 "Ferning [Type] in Cervical mucus"
* $LOINC#10574-2 "Fructose [Moles/volume] in Semen"
* $LOINC#10575-9 "Deprecated Gamma glutamyl transferase [Enzymatic activity/volume] in Semen"
* $LOINC#10576-7 "Germ cells.immature [#/volume] in Semen"
* $LOINC#10577-5 "Glucosidase [Enzymatic activity/volume] in Seminal plasma"
* $LOINC#10578-3 "Glycerophosphocholine [Moles/volume] in Seminal plasma"
* $LOINC#10579-1 "Leukocytes [#/volume] in Semen"
* $LOINC#1058-7 "I Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10580-9 "Liquefaction [Time] in Semen"
* $LOINC#10581-7 "Deprecated Number of entities [#] in Spermatozoa"
* $LOINC#10582-5 "pH of Cervical mucus"
* $LOINC#10583-3 "Prostaglandin F1 alpha [Moles/volume] in Semen"
* $LOINC#10584-1 "Deprecated Protein [Mass/volume] in Semen"
* $LOINC#10585-8 "Round cells [#/volume] in Semen"
* $LOINC#10586-6 "Deprecated Volume of Semen"
* $LOINC#10587-4 "Sexual abstinence duration"
* $LOINC#10588-2 "Spermatogonia [#/volume] in Semen"
* $LOINC#10589-0 "Spermatids [#/volume] in Semen by Streptoavidin-biotin method (SAB)"
* $LOINC#1059-5 "I Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10590-8 "Spermatids [#/volume] in Semen by Sertoli cell barrier method (SCB)"
* $LOINC#10591-6 "Primary Spermatocytes [#/volume] in Semen"
* $LOINC#10592-4 "Secondary Spermatocytes [#/volume] in Semen"
* $LOINC#10593-2 "Spermatozoa Pyriform Head/100 spermatozoa in Semen"
* $LOINC#10594-0 "Spermatozoa Tapering Head/100 spermatozoa in Semen"
* $LOINC#10595-7 "Deprecated Spermatozoa [#/volume] in Semen"
* $LOINC#10596-5 "Deprecated Spermatozoa Ab in cervical mucosa"
* $LOINC#10597-3 "Deprecated Spermatozoa Ab in semen"
* $LOINC#10598-1 "Deprecated Spermatozoa Ab in serum"
* $LOINC#10599-9 "Spermatozoa penetration [Presence] in Seminal fluid and Cervical mucosa by Kremer test"
* $LOINC#106-5 "Ceforanide [Susceptibility] by Serum bactericidal titer"
* $LOINC#1060-3 "I Ab [Presence] in Serum or Plasma"
* $LOINC#10600-5 "Spermatozoa penetration [Presence] in Seminal fluid and Cervical mucosa"
* $LOINC#10601-3 "Spermatozoa penetration [Presence] in Seminal fluid and Cervical mucosa --post coitus"
* $LOINC#10602-1 "Spermatozoa Abnormal Head/100 spermatozoa in Semen"
* $LOINC#10603-9 "Spermatozoa Abnormal Midpiece/100 spermatozoa in Semen"
* $LOINC#10604-7 "Spermatozoa Abnormal Tail/100 spermatozoa in Semen"
* $LOINC#10605-4 "Spermatozoa Agglutinated/100 spermatozoa in Semen"
* $LOINC#10606-2 "Spermatozoa Amorphous Head/100 spermatozoa in Semen"
* $LOINC#10607-0 "Spermatozoa Coiled Tail/100 spermatozoa in Semen"
* $LOINC#10608-8 "Spermatozoa Cytoplasmic Droplet/100 spermatozoa in Semen"
* $LOINC#10609-6 "Spermatozoa Duplicate Head/100 spermatozoa in Semen"
* $LOINC#1061-1 "Deprecated I NOS Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10610-4 "Spermatozoa Duplicate Tail/100 spermatozoa in Semen"
* $LOINC#10611-2 "Spermatozoa Immotile/100 spermatozoa in Semen"
* $LOINC#10612-0 "Spermatozoa Large Oval Head/100 spermatozoa in Semen"
* $LOINC#10613-8 "Spermatozoa Viable/100 spermatozoa in Semen"
* $LOINC#10614-6 "Spermatozoa Motile w IgA/100 spermatozoa in Semen by Immunobead"
* $LOINC#10615-3 "Spermatozoa Motile w IgA/100 spermatozoa in Semen by Mixed antiglobulin reaction"
* $LOINC#10616-1 "Spermatozoa Motile w IgG/100 spermatozoa in Semen by Immunobead"
* $LOINC#10617-9 "Spermatozoa Motile w IgG/100 spermatozoa in Semen by Mixed antiglobulin reaction"
* $LOINC#10618-7 "Spermatozoa Motile w IgM/100 spermatozoa in Semen by Immunobead"
* $LOINC#10619-5 "Spermatozoa Motile w IgM/100 spermatozoa in Semen by Mixed antiglobulin reaction"
* $LOINC#1062-9 "Deprecated I NOS Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10620-3 "Spermatozoa Nonprogressive/100 spermatozoa in Semen"
* $LOINC#10621-1 "Spermatozoa Normal Head/100 spermatozoa in Semen"
* $LOINC#10622-9 "Spermatozoa Normal/100 spermatozoa in Semen"
* $LOINC#10623-7 "Spermatozoa Pin Head/100 spermatozoa in Semen"
* $LOINC#10624-5 "Spermatozoa Rapid/100 spermatozoa in Semen"
* $LOINC#10625-2 "Spermatozoa Round Head/100 spermatozoa in Semen"
* $LOINC#10626-0 "Spermatozoa Slow/100 spermatozoa in Semen"
* $LOINC#10627-8 "Spermatozoa Small Oval Head/100 spermatozoa in Semen"
* $LOINC#10628-6 "Spermatozoa Tail Swelling/100 spermatozoa in Semen"
* $LOINC#10629-4 "Spermatozoa Vacuolated Head/100 spermatozoa in Semen"
* $LOINC#1063-7 "Deprecated I NOS Ab [Presence] in Serum or Plasma"
* $LOINC#10630-2 "Spinnbarkeit [Length] in Cervical mucus"
* $LOINC#10631-0 "Testosterone [Moles/volume] in Semen"
* $LOINC#10632-8 "Time until next menstrual period"
* $LOINC#10633-6 "Zinc [Moles/volume] in Semen"
* $LOINC#10634-4 "Complement C1 esterase inhibitor.functional/Complement C1 esterase inhibitor.total in Serum or Plasma"
* $LOINC#10635-1 "Acanthamoeba sp identified in Eye by Organism specific culture"
* $LOINC#10636-9 "Acanthamoeba sp identified in Eye by Wet preparation"
* $LOINC#10637-7 "Microscopic observation [Identifier] in Tissue by Night blue stain"
* $LOINC#10638-5 "Thermophilic Actinomycetes colony count [#/volume] in Specimen by Organism specific culture"
* $LOINC#10639-3 "Thermophilic Actinomycetes identified in Specimen by Organism specific culture"
* $LOINC#1064-5 "Deprecated I NOS Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10640-1 "Deprecated Adenovirus 40+41 [Identifier] in Stool by Electron microscopy"
* $LOINC#10641-9 "Amoeba identified in Aspirate by Immune stain"
* $LOINC#10642-7 "Amoeba identified in Aspirate by Wet preparation"
* $LOINC#10643-5 "Amoeba identified in Stool by Organism specific culture"
* $LOINC#10644-3 "Arthropod identified in Specimen"
* $LOINC#10645-0 "Aspergillus fumigatus Ag [Presence] in Tissue by Immunofluorescence"
* $LOINC#10646-8 "Astrovirus [Identifier] in Stool by Electron microscopy"
* $LOINC#10647-6 "Babesia sp identified in Blood by Thick film"
* $LOINC#10648-4 "Babesia sp identified in Blood by Thin film"
* $LOINC#10649-2 "Calicivirus [Identifier] in Stool by Electron microscopy"
* $LOINC#1065-2 "Deprecated I NOS Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10650-0 "Candida sp DNA [Presence] in Blood by Probe with amplification"
* $LOINC#10651-8 "Chlamydophila pneumoniae Ag [Presence] in Sputum or Bronchial"
* $LOINC#10652-6 "Chlamydophila pneumoniae DNA [Presence] in Sputum or Bronchial by Probe with amplification"
* $LOINC#10653-4 "Clotrimazole [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#10654-2 "Clotrimazole [Susceptibility] by Minimum lethal concentration (MLC)"
* $LOINC#10655-9 "Coccidia identified in Duodenal fluid by Acid fast stain"
* $LOINC#10656-7 "Coccidia identified in Stool by Acid fast stain"
* $LOINC#10657-5 "Deprecated Cryptococcus neoformans Ag [Presence] in Tissue by Immunofluorescence"
* $LOINC#10658-3 "Cyanobacterium identified in Water by Light microscopy"
* $LOINC#10659-1 "Cyclospora sp identified in Stool by Acid fast stain"
* $LOINC#1066-0 "Deprecated I NOS Ag [Presence] on Red Blood Cells"
* $LOINC#10660-9 "Cytomegalovirus Ag [Presence] in Tissue by Immune stain"
* $LOINC#10661-7 "Dinoflagellate identified in Water by Light microscopy"
* $LOINC#10662-5 "Filaria identified in Blood by Concentration"
* $LOINC#10663-3 "Filaria identified in Blood by Thick film"
* $LOINC#10664-1 "Filaria identified in Blood by Thin film"
* $LOINC#10665-8 "Fungus colony count [#/volume] in Specimen by Environmental culture"
* $LOINC#10666-6 "Fungus identified in Tissue by Fontana-Masson stain"
* $LOINC#10667-4 "Fungus identified in Specimen by Animal inoculation"
* $LOINC#10668-2 "Fungus identified in Specimen by Environmental culture"
* $LOINC#10669-0 "Fungus identified in Specimen by Sticky tape for environmental fungus"
* $LOINC#1067-8 "Jk sup(a) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10670-8 "Giardia lamblia [Presence] in Stool by Organism specific culture"
* $LOINC#10671-6 "Helminth identified in Specimen"
* $LOINC#10672-4 "Helminth+Arthropod identified in Specimen"
* $LOINC#10673-2 "Hepatitis B virus core Ag [Presence] in Tissue by Immune stain"
* $LOINC#10674-0 "Hepatitis B virus surface Ag [Presence] in Tissue by Immune stain"
* $LOINC#10675-7 "Hepatitis B virus surface Ag [Presence] in Tissue by Orcein stain"
* $LOINC#10676-5 "Hepatitis C virus RNA [Units/volume] (viral load) in Serum or Plasma by Probe with amplification"
* $LOINC#10677-3 "Herpes simplex virus 1 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10678-1 "Herpes simplex virus 1+2 Ag [Presence] in Tissue by Immune stain"
* $LOINC#10679-9 "Herpes simplex virus 2 Ag [Presence] in Tissue by Immune stain"
* $LOINC#1068-6 "Jk sup(a) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#10680-7 "Herpes simplex virus identified in Cerebral spinal fluid by Electron microscopy"
* $LOINC#10681-5 "Herpes simplex virus identified in Tissue by Electron microscopy"
* $LOINC#10682-3 "Deprecated HIV 1 RNA [Units/volume] in Serum or Plasma by Probe with amplification"
* $LOINC#10683-1 "Hydatid cyst identified in Aspirate by Immune stain"
* $LOINC#10684-9 "Hydatid cyst identified in Liver by Wet preparation"
* $LOINC#10685-6 "Hydatid cyst identified in Lung tissue by Wet preparation"
* $LOINC#10686-4 "Leishmania sp identified in Tissue by Giemsa stain"
* $LOINC#10687-2 "Leishmania sp identified in Tissue by Organism specific culture"
* $LOINC#10688-0 "Microscopic observation [Identifier] in Hair by KOH preparation"
* $LOINC#10689-8 "Microscopic observation [Identifier] in Nail by KOH preparation"
* $LOINC#1069-4 "Jk sup(a) Ab [Presence] in Serum or Plasma"
* $LOINC#10690-6 "Microsporidia identified in Duodenal fluid by Trichrome stain modified"
* $LOINC#10691-4 "Mushroom.toxic identified by Inspection"
* $LOINC#10692-2 "Mushroom.toxic identified in Food by Light microscopy"
* $LOINC#10693-0 "Mushroom.toxic identified in Vomitus by Light microscopy"
* $LOINC#10694-8 "Naegleria sp identified in Tissue by Organism specific culture"
* $LOINC#10695-5 "Naegleria sp identified in Tissue by Wet preparation"
* $LOINC#10696-3 "Norovirus [Identifier] in Stool by Electron microscopy"
* $LOINC#10697-1 "Nystatin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#10698-9 "Nystatin [Susceptibility] by Minimum lethal concentration (MLC)"
* $LOINC#10699-7 "Onchocerca sp identified in Tissue by Wet preparation"
* $LOINC#107-3 "Cefotaxime [Susceptibility] by Minimum lethal concentration (MLC)"
* $LOINC#1070-2 "Jk sup(a) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10700-3 "Orthopoxvirus [Identifier] in Skin by Electron microscopy"
* $LOINC#10701-1 "Ova and parasites identified in Stool by Concentration"
* $LOINC#10702-9 "Ova and parasites identified in Stool by Immune stain"
* $LOINC#10703-7 "Ova and parasites identified in Stool by Kinyoun iron hematoxylin stain"
* $LOINC#10704-5 "Ova and parasites identified in Stool by Light microscopy"
* $LOINC#10705-2 "Human papilloma virus Ag [Presence] in Tissue by Immune stain"
* $LOINC#10706-0 "Picornavirus [Identifier] in Stool by Electron microscopy"
* $LOINC#10707-8 "Toxic Plant identified in Plant specimen by Inspection"
* $LOINC#10708-6 "Toxic Plant identified in Vomitus by Light microscopy"
* $LOINC#10709-4 "Plasmodium falciparum Ag [Units/volume] in Blood by Immunofluorescence"
* $LOINC#1071-0 "Jk sup(a) Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#10710-2 "Plasmodium sp identified in Blood by Thin film"
* $LOINC#10711-0 "Plasmodium vivax Ag [Units/volume] in Blood by Immunofluorescence"
* $LOINC#10712-8 "Pneumocystis sp identified in Lung tissue"
* $LOINC#10713-6 "Prototheca identified in Specimen by Culture"
* $LOINC#10714-4 "Deprecated Rotavirus [Identifier] in Stool by Electron microscopy"
* $LOINC#10715-1 "Schistosoma sp identified in Urine sediment by Light microscopy"
* $LOINC#10716-9 "Schistosoma sp identified in Specimen by Organism specific culture"
* $LOINC#10717-7 "Streptococcus pneumoniae Ab [Units/volume] in Serum by Latex agglutination"
* $LOINC#10718-5 "Strongyloides sp Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#10719-3 "Taenia solium adult Ab [Units/volume] in Serum by Immunoblot"
* $LOINC#1072-8 "Jk sup(a) Ag [Presence] on Red Blood Cells"
* $LOINC#10720-1 "Terbinafine [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#10721-9 "Terbinafine [Susceptibility] by Minimum lethal concentration (MLC)"
* $LOINC#10722-7 "Torovirus [Identifier] in Stool by Electron microscopy"
* $LOINC#10723-5 "Toxoplasma gondii IgA Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#10724-3 "Toxoplasma gondii IgE Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#10725-0 "Toxoplasma gondii DNA [Units/volume] in Body fluid by Probe with amplification"
* $LOINC#10726-8 "Toxoplasma gondii [Presence] in Tissue by Giemsa stain"
* $LOINC#10727-6 "Toxoplasma gondii identified in Tissue"
* $LOINC#10728-4 "Trichomonas sp identified in Genital specimen by Organism specific culture"
* $LOINC#10729-2 "Trypanosoma sp identified in Blood by Light microscopy"
* $LOINC#1073-6 "Jk sup(b) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#10730-0 "Trypanosoma sp identified in Blood by Organism specific culture"
* $LOINC#10731-8 "Trypanosoma sp identified in Blood by Thick film"
* $LOINC#10732-6 "Trypanosoma sp identified in Blood by Thin film"
* $LOINC#10733-4 "Trypanosoma sp identified in Blood by Wet preparation"
* $LOINC#10734-2 "Varicella zoster virus identified in Skin by Electron microscopy"
* $LOINC#10735-9 "Viral sequencing [Identifier] in Serum by Sequencing"
* $LOINC#10736-7 "Virus identified in Cerebral spinal fluid by Electron microscopy"
* $LOINC#10737-5 "Virus identified in Stool by Electron microscopy"
* $LOINC#10738-3 "Virus identified in Tissue by Electron microscopy"
* $LOINC#10739-1 "Virus identified in Specimen by Electron microscopy"
* $LOINC#1074-4 "Jk sup(b) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#1075-1 "Jk sup(b) Ab [Presence] in Serum or Plasma"
* $LOINC#10753-2 "Fat.microscopic observation [Identifier] in Stool by Sudan IV stain"
* $LOINC#1076-9 "Jk sup(b) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#1077-7 "Jk sup(b) Ag [Presence] on Red Blood Cells from Donor"
* $LOINC#1078-5 "Jk sup(b) Ag [Presence] on Red Blood Cells"
* $LOINC#1079-3 "Js sup(a) Ab [Presence] in Serum or Plasma from Blood product unit"
* $LOINC#108-1 "Cefotaxime [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $LOINC#1080-1 "Js sup(a) Ab [Presence] in Serum or Plasma from Donor"
* $LOINC#1081-9 "Js sup(a) Ab [Presence] in Serum or Plasma"
* $LOINC#1082-7 "Js sup(a) Ag [Presence] on Red Blood Cells from Blood product unit"
* $LOINC#10829-0 "Silicon [Mass/volume] in Serum or Plasma"
