@startuml
alt  Consultazione documento per paziente [GET/POST]
    Consumer_DOC -> Provider: Ricerca per parametri documento
    Provider --> Consumer_DOC: GET/POST Response
else  Consultazione del documento specifico [GET/POST]
    Consumer_DOC -> Provider: Ricerca per identificativo documento
    Provider --> Consumer_DOC: GET/POST Response 
else Consultazione delle risorse LAB [GET/POST]
    Consumer_RES -> Provider: Altre consultazioni (FHIR search)
    Provider --> Consumer_RES: GET/POST Response 
end
@enduml