@startuml

Sender_DOC -> Receiver: Invio Lab Report [POST]

opt Invio FHIR Resources
   Sender_RES -> Receiver: Invio Risorse\n(DiagnosticReport, Observation, Specimen, ecc.) [POST]
end
opt
   Sender_DOC -> Receiver:  Aggiorna Lab Report [PUT]
end
opt
   Sender_RES -> Receiver:  Aggiorna Risorse [PUT]
end
alt consultazione documento FHIR 
      Consumer_DOC -> Receiver: Ricerca per paziente e/o ID prescrizione
      Consumer_DOC -> Receiver: Ricerca per paziente e/o per tipo esame
      Consumer_DOC -> Receiver: Ricerca per paziente e/o per tipo di campione
      Consumer_DOC -> Receiver: Ricerca per paziente e/o per periodo
      Consumer_DOC -> Receiver: Ricerca per paziente e/o per incontro
else consultazione risorse FHIR
      Consumer_RES -> Receiver: Ricerca tramite search parameters
end
@enduml
