@startuml
Placer -> Placer: Creazione ServiceRequest,\nEncounter

Placer -> Filler: Invio ServiceRequest,\nEncounter

alt risposta OK
    Filler -> Filler: ServiceRequest,\n Encounter status UPDATE
    Filler -> Filler: Creazione Specimen
else risposta KO
    Filler --> Placer !!: ServiceRequest status "enterer-in-error"
end

Filler -> ApplicativoClinico: Invio ServiceRequest
    loop ServiceRequest
        ApplicativoClinico-> ApplicativoClinico++: Creazione Observation,\n status=registered 
        ApplicativoClinico-> ApplicativoClinico: Generazione Risultati
        ApplicativoClinico-> ApplicativoClinico--: Aggiornamento Observation,\n status=preliminary 
    end
ApplicativoClinico-> ReportCreator: Invio Observation
ReportCreator -> ReportCreator: Validazione Observation,\n status=final
ReportCreator -> ReportCreator: Creazione DiagnosticReport
ReportCreator -> Sender: Invio  DiagnosticReport
Sender -> Placer: Recupero Patient, Practitioner, Organization, Location
Placer --> Sender: Risposta POST
Sender -> Sender: Creazione Composition
Sender -> Sender: Creazione Bundle
Sender -> Receiver: POST Bundle Laboratory Report
@enduml