@startuml
Placer -> Placer: Create ServiceRequests,Encounter

Placer -> Filler: Send ServiceRequest,Encounter

alt response OK
    Filler -> Filler: ServiceRequest, Encounter status UPDATE
    Filler -> Filler: Create Specimens
else response KO
    Filler --> Placer !!: ServiceRequest status "enterer-in-error"
end

Filler -> AutomationManager: Send ServiceRequest
    loop ServiceRequest
        AutomationManager -> AutomationManager ++: Result generation
        AutomationManager -> AutomationManager --: Create Observations 
    end
AutomationManager -> Filler: Send Observations
Filler -> Sender: Send DiagnosticReport
Sender -> Placer: Retrive Patient,Practitioner,Organization,Location
Placer --> Sender: Response POST
Sender -> Sender: Create Composition

@enduml

