@startuml
group creazione documento
 Sender -> Reciver: Creazione del Bundle document:\nPOST [base_url]/Bundle
alt success
    Reciver --> Sender: Success: 201: Created
else failure
    Reciver --> Sender: Failure: 400: Bad Request
 end
end
group consultazione documento
 Consumer -> Reciver: Consultazione del documento\n secondo CapabilityStatement:\nGET [base_url]/Bundle?[parametro]=[valore]
  alt success
 Reciver --> Consumer: Risorsa Bundle: type=searchset
 else failure
 Reciver --> Consumer: Failure: 400: Bad Request
 end 
end
group aggiornamento documento
 Sender -> Reciver: Consultazione del documento\n secondo CapabilityStatement:\nGET [base_url]/Bundle?[parametro]=[valore]
 alt success
 Reciver --> Sender: Risorsa Bundle: type=searchset
 else failure
 Reciver --> Sender: Failure: 400: Bad Request
 end
 Sender -> Reciver: Update del Bundle document:\nPUT [base_url]/Bundle/[id_Bundle]
 alt success
 Reciver --> Sender: Success: 200: OK
 else failure
 Reciver --> Sender: Failure: 400: Bad Request
 end
end
@enduml